// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFR3neu1VoSltrS3kmZi9UJme71uAi96Q',
    appId: '1:131208023746:web:69537bac28e87b9d63f55b',
    messagingSenderId: '131208023746',
    projectId: 'careasenew',
    authDomain: 'careasenew.firebaseapp.com',
    storageBucket: 'careasenew.firebasestorage.app',
    measurementId: 'G-01YGFJ8C1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSL7yfthxhEmmW96dPbfIePhpEwGK2NE',
    appId: '1:131208023746:android:9630cb7e39140ee863f55b',
    messagingSenderId: '131208023746',
    projectId: 'careasenew',
    storageBucket: 'careasenew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH723cte3C5w4m4APno3vALDRPF9MH32Q',
    appId: '1:131208023746:ios:82ec66c4422a028863f55b',
    messagingSenderId: '131208023746',
    projectId: 'careasenew',
    storageBucket: 'careasenew.firebasestorage.app',
    iosClientId: '131208023746-kluommbre0bai4p27k49b34kfo4gijdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.careasen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH723cte3C5w4m4APno3vALDRPF9MH32Q',
    appId: '1:131208023746:ios:82ec66c4422a028863f55b',
    messagingSenderId: '131208023746',
    projectId: 'careasenew',
    storageBucket: 'careasenew.firebasestorage.app',
    iosClientId: '131208023746-kluommbre0bai4p27k49b34kfo4gijdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.careasen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFR3neu1VoSltrS3kmZi9UJme71uAi96Q',
    appId: '1:131208023746:web:ed70b8163521a9ce63f55b',
    messagingSenderId: '131208023746',
    projectId: 'careasenew',
    authDomain: 'careasenew.firebaseapp.com',
    storageBucket: 'careasenew.firebasestorage.app',
    measurementId: 'G-QHQ6BKNTX2',
  );

}