import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter/services.dart';
import 'elder_detail_screen.dart';
import 'profile_screen.dart';
import 'login_screen.dart';
import 'incoming_alert_screen.dart';
import 'dart:async';

class CaregiverDashboard extends StatefulWidget {
  const CaregiverDashboard({super.key});

  @override
  State<CaregiverDashboard> createState() => _CaregiverDashboardState();
}

class _CaregiverDashboardState extends State<CaregiverDashboard> {
  final user = FirebaseAuth.instance.currentUser;
  List<String> clusterIds = [];
  bool isLoading = true;
  String caregiverName = '';
  final List<StreamSubscription> _alertSubscriptions = [];
  final Set<String> _shownAlerts = {};

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    setState(() => isLoading = true);
    try {
      final userDoc = await FirebaseFirestore.instance
          .collection('users')
          .doc(user!.uid)
          .get();

      final data = userDoc.data();
      if (data != null) {
        caregiverName = data['name'] ?? 'Caregiver';
        final ids = data['clusterIds'];
        if (ids is List) {
          clusterIds = List<String>.from(ids);
        }
      }
    } catch (e) {
      debugPrint('Error loading caregiver dashboard: $e');
    } finally {
      if (mounted) setState(() => isLoading = false);
      _setupAlertListeners();
    }
  }

  void _setupAlertListeners() {
    for (var sub in _alertSubscriptions) {
      sub.cancel();
    }
    _alertSubscriptions.clear();

    for (String cId in clusterIds) {
      final sub = FirebaseFirestore.instance
          .collection('elderClusters')
          .doc(cId)
          .collection('alerts')
          .where('resolved', isEqualTo: false)
          .snapshots()
          .listen((snapshot) async {
        for (var change in snapshot.docChanges) {
          if (change.type == DocumentChangeType.added) {
            final alertId = change.doc.id;
            final alertData = change.doc.data();
            
            if (alertData != null && 
               (alertData['type'] == 'SOS' || alertData['type'] == 'CALL_REQUEST') && 
               !_shownAlerts.contains(alertId)) {
               
               _shownAlerts.add(alertId);
               
               final clusterDoc = await FirebaseFirestore.instance.collection('elderClusters').doc(cId).get();
               final eId = clusterDoc.data()?['elderId'];
               String eName = "Elder";
               if (eId != null) {
                  final profile = await FirebaseFirestore.instance.collection('users').doc(eId).collection('profile').doc(eId).get();
                  eName = profile.data()?['name'] ?? "Elder";
               }

               if (mounted) {
                 Navigator.push(
                   context,
                   MaterialPageRoute(
                     builder: (_) => IncomingAlertScreen(
                       clusterId: cId,
                       alertId: alertId,
                       elderName: eName,
                       alertType: alertData['type'],
                     )
                   )
                 );
               }
            }
          }
        }
      });
      _alertSubscriptions.add(sub);
    }
  }

  @override
  void dispose() {
    for (var sub in _alertSubscriptions) {
      sub.cancel();
    }
    super.dispose();
  }

  void _showAddElderDialog() {
    final codeController = TextEditingController();
    
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Add an Elder'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text('Enter the Cluster Invite Code generated by the Elder to start monitoring them.'),
            const SizedBox(height: 16),
            TextField(
              controller: codeController,
              decoration: const InputDecoration(
                labelText: 'Invite Code',
                border: OutlineInputBorder(),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              if (codeController.text.trim().isEmpty) return;
              
              Navigator.pop(context);
              setState(() => isLoading = true);
              
              try {
                final clusterId = codeController.text.trim();
                final clusterDoc = await FirebaseFirestore.instance.collection('elderClusters').doc(clusterId).get();
                
                if (!clusterDoc.exists) {
                   if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Invalid Invite Code.')));
                   setState(() => isLoading = false);
                   return;
                }
                
                // Add caregiver to cluster
                await FirebaseFirestore.instance.collection('elderClusters').doc(clusterId).update({
                  'primaryCaregiverId': user!.uid,
                });
                
                // Add cluster to caregiver user doc
                await FirebaseFirestore.instance.collection('users').doc(user!.uid).update({
                  'clusterIds': FieldValue.arrayUnion([clusterId]),
                });
                
                _loadData(); // reload
              } catch (e) {
                 if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error joining: $e')));
                 setState(() => isLoading = false);
              }
            },
            child: const Text('Join Cluster'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    if (isLoading) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }

    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.background,
      appBar: AppBar(
        title: Row(
          children: [
            const Icon(Icons.favorite, color: Colors.teal),
            const SizedBox(width: 8),
            const Text("Elders Overview", style: TextStyle(fontWeight: FontWeight.bold)),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.person),
            onPressed: () {
              Navigator.push(context, MaterialPageRoute(builder: (_) => const ProfileScreen(role: 'caregiver')))
                .then((_) => _loadData());
            },
          ),
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () async {
              await FirebaseAuth.instance.signOut();
              if (mounted) {
                Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const LoginScreen()));
              }
            },
          )
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _showAddElderDialog,
        icon: const Icon(Icons.add, color: Colors.white),
        label: const Text('Add Elder', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        backgroundColor: Theme.of(context).colorScheme.primary,
      ).animate().slideY(begin: 1.0, curve: Curves.easeOutBack, duration: 600.ms),
      body: clusterIds.isEmpty
          ? Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.family_restroom, size: 80, color: Colors.grey.shade400).animate().scale(),
                  const SizedBox(height: 16),
                  Text("No elders added yet.", style: TextStyle(fontSize: 20, color: Colors.grey.shade600)).animate().fade(delay: 200.ms),
                  const SizedBox(height: 8),
                  Text("Tap 'Add Elder' to join an elder's cluster.", style: TextStyle(color: Colors.grey.shade500)).animate().fade(delay: 300.ms),
                ],
              ),
            )
          : RefreshIndicator(
              onRefresh: _loadData,
              child: ListView.builder(
                padding: const EdgeInsets.all(20),
                itemCount: clusterIds.length,
                itemBuilder: (context, index) {
                  return FutureBuilder<DocumentSnapshot>(
                    future: FirebaseFirestore.instance.collection('elderClusters').doc(clusterIds[index]).get(),
                    builder: (context, snapshot) {
                      if (!snapshot.hasData) return const Card(child: Padding(padding: EdgeInsets.all(20), child: Center(child: CircularProgressIndicator())));
                      
                      final clusterData = snapshot.data!.data() as Map<String, dynamic>?;
                      if (!snapshot.data!.exists || clusterData == null) {
                        return const SizedBox.shrink(); // Invalid cluster
                      }
                      
                      final elderId = clusterData['elderId'];
                      final clusterId = snapshot.data!.id;

                      return FutureBuilder<DocumentSnapshot>(
                        future: FirebaseFirestore.instance.collection('users').doc(elderId).collection('profile').doc(elderId).get(),
                        builder: (context, profileSnapshot) {
                          String elderName = "Loading...";
                          if (profileSnapshot.connectionState == ConnectionState.done) {
                            elderName = (profileSnapshot.data?.data() as Map<String, dynamic>?)?['name'] ?? 'Elder Profiles Missing';
                          }

                          return _buildElderCard(context, clusterId, elderName, elderId)
                            .animate().fade(duration: 400.ms, delay: (index * 100).ms).slideX(begin: 0.1);
                        },
                      );
                    },
                  );
                },
              ),
            ),
    );
  }

  Widget _buildElderCard(BuildContext context, String clusterId, String elderName, String elderId) {
    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 4,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: InkWell(
        borderRadius: BorderRadius.circular(20),
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => ElderDetailScreen(clusterId: clusterId, elderName: elderName),
            ),
          );
        },
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Row(
                children: [
                  const CircleAvatar(
                    radius: 30,
                    backgroundColor: Colors.teal,
                    child: Icon(Icons.person, color: Colors.white, size: 36),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(elderName, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold)),
                        const SizedBox(height: 4),
                        // Get active SOS status
                        StreamBuilder<QuerySnapshot>(
                          stream: FirebaseFirestore.instance
                              .collection('elderClusters')
                              .doc(clusterId)
                              .collection('alerts')
                              .where('resolved', isEqualTo: false)
                              .snapshots(),
                          builder: (context, snapshot) {
                            if (!snapshot.hasData) return const Text('Checking alerts...', style: TextStyle(color: Colors.grey));
                            
                            if (snapshot.data!.docs.isNotEmpty) {
                              return Row(
                                children: [
                                  const Icon(Icons.warning, color: Colors.red, size: 16),
                                  const SizedBox(width: 4),
                                  Text("${snapshot.data!.docs.length} Active Alert(s)", style: const TextStyle(color: Colors.red, fontWeight: FontWeight.bold)),
                                ],
                              );
                            }
                            return Row(
                              children: [
                                Icon(Icons.check_circle, color: Colors.green.shade600, size: 16),
                                const SizedBox(width: 4),
                                Text("All clear", style: TextStyle(color: Colors.green.shade600, fontWeight: FontWeight.bold)),
                              ],
                            );
                          },
                        ),
                      ],
                    ),
                  ),
                  const Icon(Icons.chevron_right, color: Colors.grey),
                ],
              ),
              const SizedBox(height: 16),
              const Divider(color: Colors.black12),
              const SizedBox(height: 8),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  _buildMiniAction(Icons.medication, "Meds", Colors.blue),
                  _buildMiniAction(Icons.checklist, "Tasks", Colors.green),
                  _buildMiniAction(Icons.bar_chart, "Health", Colors.purple),
                  _buildMiniAction(Icons.notifications_active, "Alerts", Colors.orange),
                ],
              )
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildMiniAction(IconData icon, String label, Color color) {
    return Column(
      children: [
        Icon(icon, color: color, size: 24),
        const SizedBox(height: 4),
        Text(label, style: TextStyle(color: Colors.grey.shade700, fontSize: 12, fontWeight: FontWeight.w600)),
      ],
    );
  }
}
